apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends-deploy
  namespace: {{ .Values.namespace.name }}
  labels:
    app: techtrends
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends-container
        image: {{ .Values.image.repository }} :{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: {{ .Values.containers.livenessProbe.httpGet.path }}
            port: {{ .Values.containers.livenessProbe.httpGet.port }}
        readinessProbe:
          httpGet:
            path: {{ .Values.containers.readinessProbe.httpGet.path }}
            port: {{ .Values.containers.readinessProbe.httpGet.port }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        ports:
        - containerPort: {{ .Values.containers.ports.containerPort }}