apiVersion: v1
kind: Service
metadata:
  name: techtrends-service
  namespace: sandbox
  labels:
    app: techtrends
spec:
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  selector:
    app: techtrends
  type: ClusterIP